name: inception

services:
  mariadb:
    init: true
    container_name: mariadb
    image: mariadb:42
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - GRAFANA_DATABASE
        - MYSQL_USER
        - MYSQL_USER_PASSWORD
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - inception

  nginx:
    init: true
    container_name: nginx
    image: nginx:42
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME
        - CERT_KEY_PATH
        - CERT_CRT_PATH
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb

  wordpress:
    init: true
    container_name: wordpress
    image: wordpress:42
    build: 
      context: ./requirements/wordpress
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_USER_PASSWORD
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb
  
  # BONUS SERVICES
  static:
    init: true
    container_name: static
    image: static:42
    build:
      context: ./requirements/bonus/static
    restart: always
    networks:
      - inception
    ports:
      - "4173:4173"
  
  vsftpd:
    container_name: vsftpd
    image: vsftpd:42
    build: ./requirements/bonus/vsftpd
    env_file:
      - .env
    volumes:
      - wordpress:/wordpress
    restart: always
    networks:
      - inception
    ports:
      - "21:21"
      - "21000-21100:21000-21100"
    depends_on:
      - wordpress
  
  redis:
    init: true
    container_name: redis
    image: redis:42
    build: ./requirements/bonus/redis
    restart: always
    networks:
      - inception

  adminer:
    init: true
    container_name: adminer
    image: adminer:42
    build: ./requirements/bonus/adminer
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    
  grafana:
    init: true
    container_name: grafana
    image: grafana:42
    build: 
      context: ./requirements/bonus/grafana
      args:
        - GRAFANA_DATABASE
        - MYSQL_USER
        - MYSQL_USER_PASSWORD
    env_file:
      - .env
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/mguardia/data/mariadb
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/mguardia/data/wordpress
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
