name: inception

#cosas que seguramente use en services:
    # especificar archivo .env
    # env_file: .env
    # tini - PID 1
    # init: true
    # exponer puertos para conectar servicios. NO se deben exponer al host (si se exponen en el dockerfile no hace falta ponerlo aqui)
    # expose:
    #   - "3306"
    #   - "9000"
    # volumes:
    #   - type: volume
    #     source: db-data
    #     target: /data
    #     volume:
    #       nocopy: true
    #       subpath: sub
    #   - type: bind
    #     source: /var/run/postgres/postgres.sock
    #     target: /var/run/postgres/postgres.sock


services:
  mariadb:
    init: true
    image: mariadb:42
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_USER_PASSWORD
    container_name: mariadb
    restart: always
    networks:
      - inception
#   nginx:
#     init: true
#     build: ./requirements/nginx
#     container_name: nginx
#     restart: always
#     ports:
#       - "443:80"
#     depends_on:
#       - wordpress
#     networks:
#       - inception

  wordpress:
    init: true
    image: wordpress:42
    build: 
      context: ./requirements/wordpress
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_USER_PASSWORD

    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception

# volumes:


networks:
  inception:
    name: inception
