name: inception

#cosas que seguramente use en services:
    # especificar archivo .env
    # env_file: .env
    # tini - PID 1
    # init: true
    # exponer puertos para conectar servicios. NO se deben exponer al host (si se exponen en el dockerfile no hace falta ponerlo aqui)
    # expose:
    #   - "3306"
    #   - "9000"
    # volumes:
    #   - type: volume
    #     source: db-data
    #     target: /data
    #     volume:
    #       nocopy: true
    #       subpath: sub
    #   - type: bind
    #     source: /var/run/postgres/postgres.sock
    #     target: /var/run/postgres/postgres.sock


services:
  mariadb:
    init: true
    container_name: mariadb
    image: mariadb:42
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_USER_PASSWORD
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - inception
  nginx:
    init: true
    container_name: nginx
    image: nginx:42
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME
        - CERT_KEY_PATH
        - CERT_CRT_PATH
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
  wordpress:
    init: true
    container_name: wordpress
    image: wordpress:42
    build: 
      context: ./requirements/wordpress
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_USER_PASSWORD
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/mguardia/data/mariadb
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/mguardia/data/wordpress
      o: bind


networks:
  inception:
    name: inception
    driver: bridge
